services:
  db:
    image: postgres:17.4-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - db_data:/var/lib/postgresql/data

  health-api:
    build: .
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    env_file: .env
    depends_on:
      - db

volumes:
  db_data:
