services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  health-api:
    build: .
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
